name: "Vitest Coverage Reporter"
description: "Creates a coverage report comment in pull requests using vitest coverage data"
author: "Glide Apps"
branding:
  icon: "bar-chart"
  color: "blue"

inputs:
  coverage-file:
    description: "Path to the coverage summary JSON file"
    required: false
    default: "coverage/coverage-summary.json"
  token:
    description: "GitHub token for creating comments"
    required: false
    default: "${{ github.token }}"
  title:
    description: "Title for the coverage report comment"
    required: false
    default: "📊 Coverage Report"
  show-files:
    description: "Whether to show individual file coverage details"
    required: false
    default: "true"
  coverage-threshold:
    description: "Minimum coverage percentage to consider as good (0-100)"
    required: false
    default: "80"
  make-badges:
    description: "Whether to generate coverage badges in a badges directory"
    required: false
    default: "true"
  upload-badges-to-pages:
    description: "Whether to automatically upload badges to GitHub Pages branch"
    required: false
    default: "true"
  pages-branch:
    description: "Branch to upload badges to for GitHub Pages"
    required: false
    default: "gh-pages"
  pages-badges-dir:
    description: "Directory within the pages branch to store badges"
    required: false
    default: "badges"

runs:
  using: "node20"
  main: "github-action/action.js"
