name: Coverage Report with Badge Upload
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: write # Required for GitHub Pages upload

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test

      # Coverage reporting (runs on PRs and main)
      - name: Report Coverage
        uses: glideapps/vitest-v8-json-coverage-summary@v0.0.0-echo
        with:
          coverage-file: "coverage/coverage-summary.json"
          title: "🧪 Test Coverage Report"
          show-files: "true"
          coverage-threshold: "80"

  # Note: Badge generation and upload functionality is not yet available in this action
  # This example will be updated when badge functionality is properly implemented
