name: Badge Uploader Only
on:
  push:
    branches: [main]

permissions:
  contents: write # Required for GitHub Pages upload

jobs:
  upload-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git operations

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test

      # Upload badges to GitHub Pages (generates badges automatically)
      - name: Upload Badges to GitHub Pages
        uses: glideapps/vitest-v8-json-coverage-summary/actions/badge-uploader@v0.0.0-echo
        with:
          coverage-file: "coverage/coverage-summary.json"
          badges-dir: "badges"
          pages-branch: "gh-pages"
          pages-badges-dir: "badges"
          generate-badges: "true"
