name: Full Coverage Workflow
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: write # Required for GitHub Pages upload

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test

      # Coverage reporting (runs on PRs and main)
      - name: Report Coverage
        uses: glideapps/vitest-v8-json-coverage-summary@v0.0.0-echo
        with:
          coverage-file: "coverage/coverage-summary.json"
          title: "🧪 Test Coverage Report"
          show-files: "true"
          coverage-threshold: "80"

  # Badge generation and upload (only runs on main branch)
  badges:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git operations

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test

      # Generate badges
      - name: Generate Badges
        uses: ./actions/badge-generator
        with:
          coverage-file: "coverage/coverage-summary.json"
          badges-dir: "badges"

      # Upload badges to GitHub Pages
      - name: Upload Badges to GitHub Pages
        uses: ./actions/badge-uploader
        with:
          badges-dir: "badges"
          pages-branch: "gh-pages"
          pages-badges-dir: "badges"
          generate-badges: "false" # Use existing badges
