name: Example Coverage Workflow
on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: write # Required for GitHub Pages upload

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test

      - name: Report Coverage
        uses: ./
        with:
          coverage-file: "coverage/coverage-summary.json"
          title: "🧪 Test Coverage Report"
          show-files: "true"
          coverage-threshold: "80"
          make-badges: "true"
          upload-badges-to-pages: "true"
          pages-branch: "gh-pages"
          pages-badges-dir: "badges"
