name: Test Coverage Action

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm ci || (rm -rf node_modules package-lock.json && npm install)

      - name: Run tests with coverage
        run: npm test

      - name: Report Coverage
        uses: ./
        with:
          coverage-file: "coverage/coverage-summary.json"
          title: "🧪 Test Coverage Report"
          show-files: "true"
          coverage-threshold: "80"
